version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: certifyx-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: certifyx
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: certifyx-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/certifyx?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key
      - MODULE_ADDRESS=0x1
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: .
    container_name: certifyx-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data: