[package]
name = "CertifyX"
version = "1.0.0"
authors = ["CertifyX Team"]

[addresses]
certifyx = "0x99f9ffaaa037851fa145a6eea15bd4572019848daa7559b3a47f0e409ca2866a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]